services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: loan_api
    ports:
      - "9500:9500"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: loan_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:9500